####### WHOLE FILE GENERATED BY LLM (Claude) ###########
#!/usr/bin/env python3
"""
Script to run all unit tests and generate a coverage report
"""
import os
import sys
import subprocess

def run_tests():
    """Run pytest with coverage reporting"""
    # Change to the project root directory if needed
    #os.chdir(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
    
    print("Running tests with pytest...")
    
    # Run tests and generate coverage report
    result = subprocess.run([
        "python", "-m", "pytest",
        "--cov=.",
        "--cov-report=term",
        "--cov-report=html:coverage_html",
        "tests/",
        "-v"
    ], capture_output=True, text=True)
    
    # Print the output
    print(result.stdout)
    if result.stderr:
        print("Errors:")
        print(result.stderr)
    
    # Return the exit code
    return result.returncode

if __name__ == "__main__":
    sys.exit(run_tests())